name: PromptCheck Example Workflow

on:
  pull_request:
    branches:
      - main # Or your default development branch
  push:
    branches:
      - main # Or your default development branch
  # workflow_dispatch: # Optional: allow manual triggering

jobs:
  evaluate_prompts:
    name: Run PromptCheck Evaluations
    runs-on: ubuntu-latest
    permissions:
      contents: read # Needed to checkout the repository
      pull-requests: write # Needed to post comments on PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Or your preferred Python version for promptcheck
      
      - name: Install PromptCheck
        run: |
          # Install from PyPI once available, e.g.:
          # pip install "promptcheck[bleu]" # Add [bleu] if you use BLEU metric
          # For now, using TestPyPI as an example:
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple "promptcheck[bleu]==0.0.1a0"
          # Replace with: pip install "promptcheck[bleu]" once on PyPI

      - name: Run PromptCheck Evaluations
        # This step assumes your test files are in a 'tests/' directory
        # and your config (if any, for API keys) is promptcheck.config.yaml in the root.
        # Adjust paths as needed for your project structure.
        run: promptcheck run --soft-fail --output-dir promptcheck_results/ tests/
        env:
          # Add your LLM provider API keys as secrets in your GitHub repository settings
          # Example for OpenRouter:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          # OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: Post PR Comment with PromptCheck Results
        # This step requires a script (e.g., scripts/post_comment.py in the promptcheck repo)
        # to parse the results and post a comment. You would need to include such a 
        # script in your own repository or use a published GitHub Action for this.
        # As a placeholder, this shows how it *could* be invoked if you had the script.
        if: github.event_name == 'pull_request' && always() # always() ensures it runs even if prior steps fail (due to --soft-fail)
        run: |
          echo "Attempting to post PR comment..."
          # Assuming you have a results file, e.g., promptcheck_results/promptcheck_run_*.json
          # And a script like https://github.com/b00gn1sh/promptcheck/blob/main/scripts/post_comment.py
          # (You would need to copy or adapt this script into your own repository)
          # Example invocation (if script is at ./scripts/post_comment.py):
          # python ./scripts/post_comment.py promptcheck_results/promptcheck_run_*.json
          echo "(Placeholder for PR comment posting logic - adapt post_comment.py from promptcheck repo)"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Upload PromptCheck Results Artifact
        if: always() # Always run to upload results, even if tests failed (due to --soft-fail)
        uses: actions/upload-artifact@v4
        with:
          name: promptcheck-evaluation-results
          path: promptcheck_results/
          if-no-files-found: warn 