name: EvalLoop Self-Test

on:
  push:
    branches:
      - main # Or your default branch
  pull_request:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  run_evalloop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run EvalLoop Action 
        id: evalloop_run
        uses: ./ # Uses the action in the current repository
        env:
          DOCKER_BUILDKIT: 0 # Attempt to influence docker build if uses: ./ respects it for its own build step.
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        with:
          test_path: 'tests/basic_example.yaml'
          config_dir: '.'
          output_dir: 'evalloop-action-results'

      - name: Upload EvalLoop Results
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: evalloop-results-artifact
          path: evalloop-action-results/ # This path is inside the runner, where docker run might create it.
          if-no-files-found: warn 

      - name: Print run.json path (for debugging)
        if: always()
        run: |
          echo "Path to run.json from action output: ${{ steps.evalloop_run.outputs.run_json_path }}"
          echo "Listing contents of output directory:"
          ls -R evalloop-action-results/ 