name: EvalLoop Self-Test

on:
  push:
    branches:
      - main # Or your default branch
  pull_request:
    branches:
      - main # Or your default branch
  workflow_dispatch: # Allows manual triggering

jobs:
  run_evalloop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List context before Docker build
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing contents:"
          ls -ARlhp .
          echo "Listing src contents:"
          ls -ARlhp ./src || echo "src directory not found or empty"
          echo "Listing tests contents:"
          ls -ARlhp ./tests || echo "tests directory not found or empty"

      - name: Build Docker image (BuildKit disabled for clearer errors)
        env:
          DOCKER_BUILDKIT: 0 # Disable BuildKit
        run: docker build --tag evalloop-action --file Dockerfile .

      - name: Run EvalLoop via Docker (custom)
        id: evalloop_run
        run: |
          docker run --name evallooprunner \
            --workdir /github/workspace \
            -v "${{ github.workspace }}":/github/workspace \
            -e INPUT_TEST_PATH='${{ inputs.test_path || 'tests/basic_example.yaml' }}' \
            -e INPUT_CONFIG_DIR='${{ inputs.config_dir || '.' }}' \
            -e INPUT_OUTPUT_DIR='${{ inputs.output_dir || 'evalloop-action-results' }}' \
            -e OPENROUTER_API_KEY='${{ secrets.OPENROUTER_API_KEY }}' \
            -e GITHUB_OUTPUT='${{ steps.evalloop_run.outputs.run_json_path }}' \
            evalloop-action
            # The GITHUB_OUTPUT redirect inside docker run is tricky and might not work as intended for job outputs.
            # The entrypoint.sh is responsible for writing to $GITHUB_OUTPUT for action outputs.
            # We need to ensure entrypoint.sh correctly receives and uses $GITHUB_OUTPUT path.

      - name: Upload EvalLoop Results
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: evalloop-results-artifact
          path: evalloop-action-results/ # This path is inside the runner, where docker run might create it.
          if-no-files-found: warn 

      - name: Print run.json path (for debugging)
        if: always()
        run: |
          echo "Path to run.json from action output: ${{ steps.evalloop_run.outputs.run_json_path }}"
          echo "Listing contents of output directory:"
          ls -R evalloop-action-results/ 